# Generated by Django 2.2.14 on 2022-05-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='max_qty',
            field=models.IntegerField(default=1),
        ),
    ]
